### ISSUE TITLE
Typo: Script doesn't kill stock launcher process

### ISSUE THREAD

**Issue by alairon** [Arks-Layer/PSO2WinstoreFix#20]
There is a minor typo on line 1003 of the PS script at "pso2laucher" that prevents the script from killing the stock launcher process.
This typo also appears on the `pso2_winstore_fix_freshinstall.ps1` script from the [Tweaker install guide](https://na.arks-layer.com/tweaker-setup-b.html).

https://github.com/Arks-Layer/PSO2WinstoreFix/blob/1f71fff953cd607c38f7cac6f39a05d59e6516fe/pso2_winstore_fix.ps1#L1003

**Comment by Aida-Enna** [comment]
Sorry, I must have had notifications off for issues on here or something, I never saw this. Empjustine fixed it though, thanks!

**Comment by alairon** [comment]
Thanks for fixing it! Will the script found on the tweaker guide be updated as well? Right now it points to a file hosted on the Arks Layer site and doesn't seem to include this fix.
